version: '3'
services:
  ftp_server:
    image: stilliard/pure-ftpd
    environment:
      FTP_USER_NAME: user1
      FTP_USER_PASS: 123
      FTP_USER_HOME: /home/user
    ports:
      - "21:21"
      - "30000-30009:30000-30009"